//USER REDUCER TYPES
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";
export const MARK_NOTIFICATIONS_AS_READ = "MARK_NOTIFICATIONS_AS_READ";
//UI REDUCER TYPES
export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOADING_DATA = "LOADING_DATA";
export const STOP_LOADING_UI = "STOP_LOADING_UI";
//DATA REDUCER TYPES
export const SET_POSTS = "SET_POSTS";
export const SET_POST = "SET_POST";
export const LIKE_POST = "LIKE_POST";
export const UNLIKE_POST = "UNLIKE_POST";
export const DISLIKE_POST = "DISLIKE_POST";
export const UNDISLIKE_POST = "UNDISLIKE_POST";
export const DELETE_POST = "DELETE_POST";
export const NEW_POST = "NEW_POST";
export const NEW_COMMENT = "NEW_COMMENT";
export const SET_ROOTCOMMENTS = "SET_ROOTCOMMENTS";
export const COIN_POST = "COIN_POST";
export const UNCOIN_POST = "UNCOIN_POST";
export const SET_COINS = "SET_COINS";
export const CLEAR_RECENTLY_AUTHORED = "CLEAR_RECENTLY_AUTHORED";

export const COIN_COMMENT = "COIN_COMMENT";
export const UNCOIN_COMMENT = "UNCOIN_COMMENT";

export const LIKE_COMMENT = "LIKE_COMMENT";
export const UNLIKE_COMMENT = "UNLIKE_COMMENT";
export const DISLIKE_COMMENT = "DISLIKE_COMMENT";
export const UNDISLIKE_COMMENT = "UNDISLIKE_COMMENT";
